#-------------------------------------------------------------------------------
# Adjust this according to your main document filename (in this directory)!
# This document filename is used by the "make" command.

# exports COMPONENT_NAME as used in the local doxyfile
export COMPONENT_NAME=XGbE_lib
#-------------------------------------------------------------------------------

# Include the Makefile in the template directory.
include config/Makefile
